name: stock

on:
  push:
    branches: [ main ] 

jobs:
  veri_analizi:
    runs-on: ubuntu-latest 

    steps:
    - name: 
      uses: actions/checkout@v2 
    - name: Python kur
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  

    - name: 
      run: ls -l  

    - name: CSV test
      run: |
        if [ ! -f orcl.csv ]; then
          echo "orcl.csv dosyası bulunamadı!"
          exit 1
        fi

    - name: Script
      run: |
        python main.py  # 'main.py' betiğini çalıştırır.
        if [ ! -f orcl-sma.csv ] || [ ! -f orcl-rsi.csv ]; then
         
        fi

    - name: SMA 
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: sma
        path: orcl-sma.csv  

    - name: RSI 
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rsi
        path: orcl-rsi.csv  
